# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shippinglogic}
  s.version = "1.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Johnson of Binary Logic"]
  s.date = %q{2010-09-04}
  s.description = %q{Easily use FedEx, UPS, USPS web services with an elegant and simple syntax.}
  s.email = %q{bjohnson@binarylogic.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "init.rb",
     "lib/shippinglogic.rb",
     "lib/shippinglogic/attributes.rb",
     "lib/shippinglogic/error.rb",
     "lib/shippinglogic/fedex.rb",
     "lib/shippinglogic/fedex/cancel.rb",
     "lib/shippinglogic/fedex/enumerations.rb",
     "lib/shippinglogic/fedex/error.rb",
     "lib/shippinglogic/fedex/rate.rb",
     "lib/shippinglogic/fedex/request.rb",
     "lib/shippinglogic/fedex/response.rb",
     "lib/shippinglogic/fedex/service.rb",
     "lib/shippinglogic/fedex/ship.rb",
     "lib/shippinglogic/fedex/signature.rb",
     "lib/shippinglogic/fedex/track.rb",
     "lib/shippinglogic/proxy.rb",
     "lib/shippinglogic/service.rb",
     "lib/shippinglogic/ups.rb",
     "lib/shippinglogic/ups/cancel.rb",
     "lib/shippinglogic/ups/enumerations.rb",
     "lib/shippinglogic/ups/error.rb",
     "lib/shippinglogic/ups/label.rb",
     "lib/shippinglogic/ups/rate.rb",
     "lib/shippinglogic/ups/request.rb",
     "lib/shippinglogic/ups/response.rb",
     "lib/shippinglogic/ups/service.rb",
     "lib/shippinglogic/ups/ship_accept.rb",
     "lib/shippinglogic/ups/ship_confirm.rb",
     "lib/shippinglogic/ups/track.rb",
     "lib/shippinglogic/validation.rb",
     "shippinglogic.gemspec",
     "spec/attributes_spec.rb",
     "spec/config/fedex_credentials.example.yml",
     "spec/config/ups_credentials.example.yml",
     "spec/error_spec.rb",
     "spec/fedex/cancel_spec.rb",
     "spec/fedex/error_spec.rb",
     "spec/fedex/rate_spec.rb",
     "spec/fedex/request_spec.rb",
     "spec/fedex/responses/blank.xml",
     "spec/fedex/responses/cancel_not_found.xml",
     "spec/fedex/responses/failed_authentication.xml",
     "spec/fedex/responses/malformed.xml",
     "spec/fedex/responses/rate_defaults.xml",
     "spec/fedex/responses/rate_insurance.xml",
     "spec/fedex/responses/rate_no_services.xml",
     "spec/fedex/responses/rate_non_custom_packaging.xml",
     "spec/fedex/responses/ship_defaults.xml",
     "spec/fedex/responses/ship_with_no_signature.xml",
     "spec/fedex/responses/signature_defaults.xml",
     "spec/fedex/responses/track_defaults.xml",
     "spec/fedex/responses/unexpected.xml",
     "spec/fedex/service_spec.rb",
     "spec/fedex/ship_spec.rb",
     "spec/fedex/signature_spec.rb",
     "spec/fedex/spec_helper.rb",
     "spec/fedex/track_spec.rb",
     "spec/fedex_spec.rb",
     "spec/lib/interceptor.rb",
     "spec/proxy_spec.rb",
     "spec/service_spec.rb",
     "spec/spec_helper.rb",
     "spec/ups/responses/blank.xml",
     "spec/ups/responses/track_defaults.xml",
     "spec/ups/spec_helper.rb",
     "spec/ups_spec.rb",
     "spec/validation_spec.rb"
  ]
  s.homepage = %q{http://github.com/binarylogic/shippinglogic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple and clean library to interface with shipping carriers}
  s.test_files = [
    "spec/attributes_spec.rb",
     "spec/error_spec.rb",
     "spec/fedex/cancel_spec.rb",
     "spec/fedex/error_spec.rb",
     "spec/fedex/rate_spec.rb",
     "spec/fedex/request_spec.rb",
     "spec/fedex/service_spec.rb",
     "spec/fedex/ship_spec.rb",
     "spec/fedex/signature_spec.rb",
     "spec/fedex/spec_helper.rb",
     "spec/fedex/track_spec.rb",
     "spec/fedex_spec.rb",
     "spec/lib/interceptor.rb",
     "spec/proxy_spec.rb",
     "spec/service_spec.rb",
     "spec/spec_helper.rb",
     "spec/ups/spec_helper.rb",
     "spec/ups_spec.rb",
     "spec/validation_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.4.4"])
      s.add_runtime_dependency(%q<builder>, [">= 2.1.2"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0.4.4"])
      s.add_dependency(%q<builder>, [">= 2.1.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0.4.4"])
    s.add_dependency(%q<builder>, [">= 2.1.2"])
  end
end

