require "activesupport"
require "httparty"
require "shippinglogic/proxy"
require "shippinglogic/attributes"
require "shippinglogic/validation"
require "shippinglogic/fedex"
require "shippinglogic/ups"