require "active_support"
require "httparty"
require "shippinglogic/proxy"
require "shippinglogic/attributes"
require "shippinglogic/validation"
require "shippinglogic/service"
require "shippinglogic/fedex"
require "shippinglogic/ups"